//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstWebsite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Item()
        {
            this.MemberHistories = new HashSet<MemberHistory>();
        }
    
        public int ItemsID { get; set; }
        public System.DateTime DateBorrowed { get; set; }
        public System.DateTime DateDue { get; set; }
        public Nullable<System.DateTime> DateReturned { get; set; }
        public decimal OverDueChargeDay { get; set; }
        public decimal OverDueChargeHour { get; set; }
        public decimal TransactionTotal { get; set; }
        public Nullable<System.DateTime> DatePickup { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MemberHistory> MemberHistories { get; set; }
    }
}
