//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyFirstWebsite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Library : DbContext
    {
        public Library()
            : base("name=Library")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookNumber> BookNumbers { get; set; }
        public virtual DbSet<Book> Books { get; set; }
        public virtual DbSet<ConferenceProceeding> ConferenceProceedings { get; set; }
        public virtual DbSet<ConferenceProCopy> ConferenceProCopies { get; set; }
        public virtual DbSet<DVDNumber> DVDNumbers { get; set; }
        public virtual DbSet<DVD> DVDs { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<JournalNumber> JournalNumbers { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<LibraryMember> LibraryMembers { get; set; }
        public virtual DbSet<MemberHistory> MemberHistories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Publisher> Publishers { get; set; }
        public virtual DbSet<ReferenceBookCopy> ReferenceBookCopies { get; set; }
        public virtual DbSet<ReferenceBook> ReferenceBooks { get; set; }
    }
}
